import React from "react";
import Header from "./_components/Header";
import Section from "./_components/Section";
function App() {
  const [data,setData]=React.useState([]);

  React.useEffect(()=>{
      setData(()=> { 
        return {
          "items": [
              {
                  "id": "tt13833688",
                  "rank": "1",
                  "rankUpDown": "+77",
                  "title": "The Whale",
                  "fullTitle": "The Whale (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BZTMzY2I4MmYtOWEzMi00MTE4LWJmZjctODQ0NzYyMjk1NWMzXkEyXkFqcGdeQXVyMjQwMDg0Ng@@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Darren Aronofsky (dir.), Brendan Fraser, Sadie Sink",
                  "imDbRating": "9.2",
                  "imDbRatingCount": "2215"
              },
              {
                  "id": "tt10648342",
                  "rank": "2",
                  "rankUpDown": "+26",
                  "title": "Thor: Love and Thunder",
                  "fullTitle": "Thor: Love and Thunder (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BYmMxZWRiMTgtZjM0Ny00NDQxLWIxYWQtZDdlNDNkOTEzYTdlXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Taika Waititi (dir.), Chris Hemsworth, Natalie Portman",
                  "imDbRating": "6.5",
                  "imDbRatingCount": "237712"
              },
              {
                  "id": "tt10731256",
                  "rank": "3",
                  "rankUpDown": "+15",
                  "title": "Don't Worry Darling",
                  "fullTitle": "Don't Worry Darling (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BMDMwYjY5OTItN2YyZC00Yjk3LWI4NDMtN2E5MjBhY2I3MjExXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Olivia Wilde (dir.), Florence Pugh, Olivia Wilde",
                  "imDbRating": "3.6",
                  "imDbRatingCount": "1993"
              },
              {
                  "id": "tt4593060",
                  "rank": "4",
                  "rankUpDown": "+13",
                  "title": "Pinocchio",
                  "fullTitle": "Pinocchio (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BZDIyYjM3N2EtOTU1MC00YTA4LTgzNjctMTNjODcxZTZhODU2XkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Robert Zemeckis (dir.), Joseph Gordon-Levitt, Tom Hanks",
                  "imDbRating": "5.1",
                  "imDbRatingCount": "18270"
              },
              {
                  "id": "tt3704428",
                  "rank": "5",
                  "rankUpDown": "+3",
                  "title": "Elvis",
                  "fullTitle": "Elvis (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BYzMzNTJjYmMtZTkxNS00MjI4LWI3YmQtOTQ4MDZjZDJlZjQyXkEyXkFqcGdeQXVyNjc0NzQzNTM@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Baz Luhrmann (dir.), Tom Hanks, Austin Butler",
                  "imDbRating": "7.5",
                  "imDbRatingCount": "113655"
              },
              {
                  "id": "tt1745960",
                  "rank": "6",
                  "rankUpDown": "-3",
                  "title": "Top Gun: Maverick",
                  "fullTitle": "Top Gun: Maverick (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BZWYzOGEwNTgtNWU3NS00ZTQ0LWJkODUtMmVhMjIwMjA1ZmQwXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Joseph Kosinski (dir.), Tom Cruise, Jennifer Connelly",
                  "imDbRating": "8.4",
                  "imDbRatingCount": "363479"
              },
              {
                  "id": "tt10954984",
                  "rank": "7",
                  "rankUpDown": "-6",
                  "title": "Nope",
                  "fullTitle": "Nope (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BNGM1MDc3ZjgtODlkOS00NmZjLWJlOTItNGQ5OGFhN2JlNjgxXkEyXkFqcGdeQXVyNjk1Njg5NTA@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Jordan Peele (dir.), Daniel Kaluuya, Keke Palmer",
                  "imDbRating": "7.0",
                  "imDbRatingCount": "115407"
              },
              {
                  "id": "tt15083184",
                  "rank": "8",
                  "rankUpDown": "+2",
                  "title": "I Came By",
                  "fullTitle": "I Came By (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BMzhjOWRmMGMtZjExNy00M2IxLWFmODQtM2I1MzBmZTcwOTgwXkEyXkFqcGdeQXVyNTg1MDQzMDU@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Babak Anvari (dir.), Antonio Aakeel, Alicia Ambrose-Bayly",
                  "imDbRating": "6.1",
                  "imDbRatingCount": "13715"
              },
              {
                  "id": "tt15325794",
                  "rank": "9",
                  "rankUpDown": "-2",
                  "title": "Fall",
                  "fullTitle": "Fall (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BNGI3MWYwYjItNzZhYi00ZWIzLTkyMzYtN2JmNjg3ODg1NTg4XkEyXkFqcGdeQXVyMTMwMDA5ODU3._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Scott Mann (dir.), Grace Caroline Currey, Virginia Gardner",
                  "imDbRating": "6.4",
                  "imDbRatingCount": "21030"
              },
              {
                  "id": "tt15791034",
                  "rank": "10",
                  "rankUpDown": "+51",
                  "title": "Barbarian",
                  "fullTitle": "Barbarian (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BN2M3Y2NhMGYtYjUxOS00M2UwLTlmMGUtYzY4MzFlNjZkYzY2XkEyXkFqcGdeQXVyODc0OTEyNDU@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Zach Cregger (dir.), Georgina Campbell, Bill Skarsgård",
                  "imDbRating": "7.6",
                  "imDbRatingCount": "6996"
              },
              {
                  "id": "tt9411972",
                  "rank": "11",
                  "rankUpDown": "+11",
                  "title": "Where the Crawdads Sing",
                  "fullTitle": "Where the Crawdads Sing (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BMTJmNGJmYTgtYjAxNy00YmMzLTk2YTYtMGIzMmUwNDMyMTY1XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Olivia Newman (dir.), Daisy Edgar-Jones, Taylor John Smith",
                  "imDbRating": "7.1",
                  "imDbRatingCount": "28610"
              },
              {
                  "id": "tt12593682",
                  "rank": "12",
                  "rankUpDown": "-7",
                  "title": "Bullet Train",
                  "fullTitle": "Bullet Train (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BMDU2ZmM2OTYtNzIxYy00NjM5LTliNGQtN2JmOWQzYTBmZWUzXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "David Leitch (dir.), Brad Pitt, Joey King",
                  "imDbRating": "7.5",
                  "imDbRatingCount": "79107"
              },
              {
                  "id": "tt6277462",
                  "rank": "13",
                  "rankUpDown": "+483",
                  "title": "Brahmastra Part One: Shiva",
                  "fullTitle": "Brahmastra Part One: Shiva (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BOWFmZmZjNjAtZDBiNi00ZDNlLTg2YTgtZjg4ZDhlY2U0MGJhXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Ayan Mukerji (dir.), Ranbir Kapoor, Alia Bhatt",
                  "imDbRating": "5.5",
                  "imDbRatingCount": "86492"
              },
              {
                  "id": "tt11564570",
                  "rank": "14",
                  "rankUpDown": "+148",
                  "title": "Glass Onion: A Knives Out Mystery",
                  "fullTitle": "Glass Onion: A Knives Out Mystery (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BZjRjMzIxODEtZTY5NS00YWMxLTgzOGEtNmUzMzNjNWRhZThlXkEyXkFqcGdeQXVyNTA3MTU2MjE@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Rian Johnson (dir.), Daniel Craig, Edward Norton",
                  "imDbRating": "8.1",
                  "imDbRatingCount": "388"
              },
              {
                  "id": "tt5500218",
                  "rank": "15",
                  "rankUpDown": "-13",
                  "title": "Samaritan",
                  "fullTitle": "Samaritan (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BY2M2MjMxNjUtZWU2MS00NTIwLWE0ZDEtOTY3NzY5NGZmY2RmXkEyXkFqcGdeQXVyODk2NDQ3MTA@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Julius Avery (dir.), Sylvester Stallone, Javon 'Wanna' Walton",
                  "imDbRating": "5.7",
                  "imDbRatingCount": "33550"
              },
              {
                  "id": "tt0120737",
                  "rank": "16",
                  "rankUpDown": "+8",
                  "title": "The Lord of the Rings: The Fellowship of the Ring",
                  "fullTitle": "The Lord of the Rings: The Fellowship of the Ring (2001)",
                  "year": "2001",
                  "image": "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Peter Jackson (dir.), Elijah Wood, Ian McKellen",
                  "imDbRating": "8.8",
                  "imDbRatingCount": "1840976"
              },
              {
                  "id": "tt0092099",
                  "rank": "17",
                  "rankUpDown": "-11",
                  "title": "Top Gun",
                  "fullTitle": "Top Gun (1986)",
                  "year": "1986",
                  "image": "https://m.media-amazon.com/images/M/MV5BZjQxYTA3ODItNzgxMy00N2Y2LWJlZGMtMTRlM2JkZjI1ZDhhXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Tony Scott (dir.), Tom Cruise, Tim Robbins",
                  "imDbRating": "6.9",
                  "imDbRatingCount": "422267"
              },
              {
                  "id": "tt14309446",
                  "rank": "18",
                  "rankUpDown": "-14",
                  "title": "Me Time",
                  "fullTitle": "Me Time (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BNTU4YWU5YTgtODhmOC00NzU2LTkwYzQtMmJhZjRhNWQwMTJkXkEyXkFqcGdeQXVyMjIzOTA2NDk@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "John Hamburg (dir.), Kevin Hart, Mark Wahlberg",
                  "imDbRating": "5.0",
                  "imDbRatingCount": "24442"
              },
              {
                  "id": "tt15463032",
                  "rank": "19",
                  "rankUpDown": "+15",
                  "title": "Love in the Villa",
                  "fullTitle": "Love in the Villa (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BMjI5NmZmYTUtM2MzZS00ZmI0LTgyMzAtMTgwNWMyY2NjYjVkXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Mark Steven Johnson (dir.), Kat Graham, Tom Hopper",
                  "imDbRating": "5.3",
                  "imDbRatingCount": "6276"
              },
              {
                  "id": "tt8041270",
                  "rank": "20",
                  "rankUpDown": "+10",
                  "title": "Jurassic World Dominion",
                  "fullTitle": "Jurassic World Dominion (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BOTBjMjA4NmYtN2RjMi00YWZlLTliYTktOTIwMmNkYjYxYmE1XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Colin Trevorrow (dir.), Chris Pratt, Bryce Dallas Howard",
                  "imDbRating": "5.7",
                  "imDbRatingCount": "132694"
              },
              {
                  "id": "tt13223398",
                  "rank": "21",
                  "rankUpDown": "-1",
                  "title": "Beast",
                  "fullTitle": "Beast (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BMmY5MDI2YmQtNDM0YS00ZWI3LTlmM2YtYWMzNjYyOWRiZGVhXkEyXkFqcGdeQXVyMTMzODk3NDU0._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Baltasar Kormákur (dir.), Liyabuya Gongo, Martin Munro",
                  "imDbRating": "5.6",
                  "imDbRatingCount": "13430"
              },
              {
                  "id": "tt1655389",
                  "rank": "22",
                  "rankUpDown": "+25",
                  "title": "Blonde",
                  "fullTitle": "Blonde (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BNDk2YTA1MGYtMGNjMi00YTJlLWI1YjItMjBjOGJlZGIwZmYzXkEyXkFqcGdeQXVyODA0MjgyNzM@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Andrew Dominik (dir.), Ana de Armas, Lucy DeVito",
                  "imDbRating": "6.5",
                  "imDbRatingCount": "610"
              },
              {
                  "id": "tt6710474",
                  "rank": "23",
                  "rankUpDown": "+3",
                  "title": "Everything Everywhere All at Once",
                  "fullTitle": "Everything Everywhere All at Once (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BYTdiOTIyZTQtNmQ1OS00NjZlLWIyMTgtYzk5Y2M3ZDVmMDk1XkEyXkFqcGdeQXVyMTAzMDg4NzU0._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Dan Kwan (dir.), Michelle Yeoh, Stephanie Hsu",
                  "imDbRating": "8.1",
                  "imDbRatingCount": "202245"
              },
              {
                  "id": "tt11866324",
                  "rank": "24",
                  "rankUpDown": "-15",
                  "title": "Prey",
                  "fullTitle": "Prey (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BMDBlMDYxMDktOTUxMS00MjcxLWE2YjQtNjNhMjNmN2Y3ZDA1XkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Dan Trachtenberg (dir.), Amber Midthunder, Dakota Beavers",
                  "imDbRating": "7.2",
                  "imDbRatingCount": "155506"
              },
              {
                  "id": "tt4595186",
                  "rank": "25",
                  "rankUpDown": "4,700",
                  "title": "Luckiest Girl Alive",
                  "fullTitle": "Luckiest Girl Alive (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BNzJlMTE3ODEtODRjOS00Zjg4LWE0ZTYtODAwMWMwNjFmZmQyXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Mike Barker (dir.), Mila Kunis, Justine Lupe",
                  "imDbRating": "",
                  "imDbRatingCount": "0"
              },
              {
                  "id": "tt13560574",
                  "rank": "26",
                  "rankUpDown": "+5",
                  "title": "X",
                  "fullTitle": "X (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BMTJiMmE5YWItOWZjYS00YTg0LWE0MTYtMzg2ZTY4YjNkNDEzXkEyXkFqcGdeQXVyMTAzMDg4NzU0._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Ti West (dir.), Mia Goth, Jenna Ortega",
                  "imDbRating": "6.6",
                  "imDbRatingCount": "65115"
              },
              {
                  "id": "tt9198364",
                  "rank": "27",
                  "rankUpDown": "-13",
                  "title": "Three Thousand Years of Longing",
                  "fullTitle": "Three Thousand Years of Longing (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BODFjMmVmN2YtOTc5Yy00YWM0LTg0N2ItZDJiNTU5MWMyMDVlXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "George Miller (dir.), Tilda Swinton, Idris Elba",
                  "imDbRating": "6.8",
                  "imDbRatingCount": "12852"
              },
              {
                  "id": "tt12873562",
                  "rank": "28",
                  "rankUpDown": "-17",
                  "title": "The Invitation",
                  "fullTitle": "The Invitation (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BYTk3YWEwOTYtYTFiOS00NjJiLWJiOTAtMTRkZDY1Y2M1MDIyXkEyXkFqcGdeQXVyMTA3MDk2NDg2._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Jessica M. Thompson (dir.), Nathalie Emmanuel, Thomas Doherty",
                  "imDbRating": "5.3",
                  "imDbRatingCount": "5222"
              },
              {
                  "id": "tt13070038",
                  "rank": "29",
                  "rankUpDown": "+16",
                  "title": "After Ever Happy",
                  "fullTitle": "After Ever Happy (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BYWUwMjZmZGYtYjIyOS00YTY2LWFiMjMtNWYyMjdlNmUwY2FmXkEyXkFqcGdeQXVyMTUzNDkzNDY@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Castille Landon (dir.), Hero Fiennes Tiffin, Josephine Langford",
                  "imDbRating": "4.3",
                  "imDbRatingCount": "1696"
              },
              {
                  "id": "tt1758830",
                  "rank": "30",
                  "rankUpDown": "+158",
                  "title": "This Is 40",
                  "fullTitle": "This Is 40 (2012)",
                  "year": "2012",
                  "image": "https://m.media-amazon.com/images/M/MV5BNzQxMDQ1NjA4N15BMl5BanBnXkFtZTcwNTE5MjQ3OA@@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Judd Apatow (dir.), Paul Rudd, Leslie Mann",
                  "imDbRating": "6.2",
                  "imDbRatingCount": "140609"
              },
              {
                  "id": "tt11851548",
                  "rank": "31",
                  "rankUpDown": "-19",
                  "title": "Orphan: First Kill",
                  "fullTitle": "Orphan: First Kill (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BZjgwNDA3MmUtMTQ3Yy00ZDFmLTgwMTktNTBlMTQ3ZTI5MjYxXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "William Brent Bell (dir.), Isabelle Fuhrman, Julia Stiles",
                  "imDbRating": "6.0",
                  "imDbRatingCount": "20633"
              },
              {
                  "id": "tt7144666",
                  "rank": "32",
                  "rankUpDown": "-9",
                  "title": "The Black Phone",
                  "fullTitle": "The Black Phone (2021)",
                  "year": "2021",
                  "image": "https://m.media-amazon.com/images/M/MV5BMWQxOGJlNTUtYTc1YS00NDkyLWExZjItMTFiYWEzMjAzYTdjXkEyXkFqcGdeQXVyNjk1Njg5NTA@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Scott Derrickson (dir.), Mason Thames, Madeleine McGraw",
                  "imDbRating": "7.0",
                  "imDbRatingCount": "106279"
              },
              {
                  "id": "tt13640696",
                  "rank": "33",
                  "rankUpDown": "+76",
                  "title": "See How They Run",
                  "fullTitle": "See How They Run (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BNzU5OTNmZDYtZjA4OC00YmQyLTk4ZjctMzVlZTYyYTE3ODUwXkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Tom George (dir.), Kieran Hodgson, Pearl Chanda",
                  "imDbRating": "6.8",
                  "imDbRatingCount": "3156"
              },
              {
                  "id": "tt10872600",
                  "rank": "34",
                  "rankUpDown": "+6",
                  "title": "Spider-Man: No Way Home",
                  "fullTitle": "Spider-Man: No Way Home (2021)",
                  "year": "2021",
                  "image": "https://m.media-amazon.com/images/M/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Jon Watts (dir.), Tom Holland, Zendaya",
                  "imDbRating": "8.3",
                  "imDbRatingCount": "724021"
              },
              {
                  "id": "tt6443346",
                  "rank": "35",
                  "rankUpDown": "+86",
                  "title": "Black Adam",
                  "fullTitle": "Black Adam (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BNmEwODNmOTYtMWRmYS00ZTEzLWJmNTAtMWQ4OWVlMzU0MWIyXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Jaume Collet-Serra (dir.), Dwayne Johnson, Sarah Shahi",
                  "imDbRating": "",
                  "imDbRatingCount": "0"
              },
              {
                  "id": "tt10168670",
                  "rank": "36",
                  "rankUpDown": "+44",
                  "title": "Bones and All",
                  "fullTitle": "Bones and All (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BNTFiYjcyZjUtMmI4Ny00NWQ4LWI5NzctNGMyMTAxZDUzY2JlXkEyXkFqcGdeQXVyMTM1OTkyMjc4._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Luca Guadagnino (dir.), Timothée Chalamet, Taylor Russell",
                  "imDbRating": "6.6",
                  "imDbRatingCount": "342"
              },
              {
                  "id": "tt8912936",
                  "rank": "37",
                  "rankUpDown": "-12",
                  "title": "DC League of Super-Pets",
                  "fullTitle": "DC League of Super-Pets (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BZTIyNzc3NzMtNGE5YS00Yjg5LTk5MDMtOTUxMzk1ZTBkOTgwXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Jared Stern (dir.), Dwayne Johnson, Kevin Hart",
                  "imDbRating": "7.5",
                  "imDbRatingCount": "46909"
              },
              {
                  "id": "tt17076046",
                  "rank": "38",
                  "rankUpDown": "-22",
                  "title": "Weird: The Al Yankovic Story",
                  "fullTitle": "Weird: The Al Yankovic Story (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BODZmNThjMDItODE2Yy00NDNmLThiODEtZGNmZGE3MTdmMjMwXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Eric Appel (dir.), Evan Rachel Wood, Daniel Radcliffe",
                  "imDbRating": "7.7",
                  "imDbRatingCount": "138"
              },
              {
                  "id": "tt1649418",
                  "rank": "39",
                  "rankUpDown": "-18",
                  "title": "The Gray Man",
                  "fullTitle": "The Gray Man (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BOWY4MmFiY2QtMzE1YS00NTg1LWIwOTQtYTI4ZGUzNWIxNTVmXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Anthony Russo (dir.), Ryan Gosling, Chris Evans",
                  "imDbRating": "6.5",
                  "imDbRatingCount": "168885"
              },
              {
                  "id": "tt15481952",
                  "rank": "40",
                  "rankUpDown": "+59",
                  "title": "My Son Hunter",
                  "fullTitle": "My Son Hunter (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BNmJhMWFhZGQtZWJmNS00ZDA4LWIzMmEtYTM5ZGUyM2UyNjIzXkEyXkFqcGdeQXVyNzMxMzQyNDE@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Robert Davi (dir.), Laurence Fox, John James",
                  "imDbRating": "6.0",
                  "imDbRatingCount": "2499"
              },
              {
                  "id": "tt12655436",
                  "rank": "41",
                  "rankUpDown": "+10",
                  "title": "Honk for Jesus. Save Your Soul.",
                  "fullTitle": "Honk for Jesus. Save Your Soul. (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BYWUwZjNiMzQtNzZiOC00YjdjLWFiMTctOGNlMWI3ZDZkN2MxXkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Adamma Ebo (dir.), Regina Hall, Sterling K. Brown",
                  "imDbRating": "5.3",
                  "imDbRatingCount": "2149"
              },
              {
                  "id": "tt10886166",
                  "rank": "42",
                  "rankUpDown": "-10",
                  "title": "365 Days",
                  "fullTitle": "365 Days (2020)",
                  "year": "2020",
                  "image": "https://m.media-amazon.com/images/M/MV5BMDdhYzNkOWQtYWNlNi00NDdjLWJlZDMtMjJjZDYyNjAxM2U1XkEyXkFqcGdeQXVyMTQyMTMwOTk0._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Barbara Bialowas (dir.), Anna-Maria Sieklucka, Michele Morrone",
                  "imDbRating": "3.3",
                  "imDbRatingCount": "88865"
              },
              {
                  "id": "tt13314558",
                  "rank": "43",
                  "rankUpDown": "-28",
                  "title": "Day Shift",
                  "fullTitle": "Day Shift (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BYWI2ZDRjYjEtOWJiOS00NWVjLWI1MjAtNWNiMzAwNGFmNjljXkEyXkFqcGdeQXVyODEwMTc2ODQ@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "J.J. Perry (dir.), Jamie Foxx, Dave Franco",
                  "imDbRating": "6.1",
                  "imDbRatingCount": "60948"
              },
              {
                  "id": "tt19623240",
                  "rank": "44",
                  "rankUpDown": "-31",
                  "title": "Winnie-the-Pooh: Blood and Honey",
                  "fullTitle": "Winnie-the-Pooh: Blood and Honey ( 31)",
                  "year": " 31",
                  "image": "https://m.media-amazon.com/images/M/MV5BNTg2MDhhYzQtNDZjNi00MjRmLTg3NWYtMzg2ZGJkYmI2MmE0XkEyXkFqcGdeQXVyNjUxMDQ0MTg@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Rhys Waterfield (dir.), Natasha Tosini, Amber Doig-Thorne",
                  "imDbRating": "",
                  "imDbRatingCount": "0"
              },
              {
                  "id": "tt5971474",
                  "rank": "45",
                  "rankUpDown": "+268",
                  "title": "The Little Mermaid",
                  "fullTitle": "The Little Mermaid (2023)",
                  "year": "2023",
                  "image": "https://m.media-amazon.com/images/M/MV5BZWUxOGRjNTgtMjhjZC00YjRhLTk4YzEtN2IwMGFiYjZhOTBiXkEyXkFqcGdeQXVyMTA4ODY5NzE0._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Rob Marshall (dir.), Halle Bailey, Jonah Hauer-King",
                  "imDbRating": "",
                  "imDbRatingCount": "0"
              },
              {
                  "id": "tt11909878",
                  "rank": "46",
                  "rankUpDown": "+21",
                  "title": "Hocus Pocus 2",
                  "fullTitle": "Hocus Pocus 2 (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BY2NjNTgwOGUtYmY1MS00ZDQyLWJkZTAtY2Y4YWU3YjFmMjNmXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Anne Fletcher (dir.), Bette Midler, Kathy Najimy",
                  "imDbRating": "",
                  "imDbRatingCount": "0"
              },
              {
                  "id": "tt1877830",
                  "rank": "47",
                  "rankUpDown": "-9",
                  "title": "The Batman",
                  "fullTitle": "The Batman (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BMDdmMTBiNTYtMDIzNi00NGVlLWIzMDYtZTk3MTQ3NGQxZGEwXkEyXkFqcGdeQXVyMzMwOTU5MDk@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Matt Reeves (dir.), Robert Pattinson, Zoë Kravitz",
                  "imDbRating": "7.9",
                  "imDbRatingCount": "593892"
              },
              {
                  "id": "tt12262116",
                  "rank": "48",
                  "rankUpDown": "-19",
                  "title": "Thirteen Lives",
                  "fullTitle": "Thirteen Lives (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BNzI4YzkyMTYtYmQ1MC00NjYwLThkMDgtY2E1Njg1MTAzZWJhXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Ron Howard (dir.), Viggo Mortensen, Colin Farrell",
                  "imDbRating": "7.8",
                  "imDbRatingCount": "40456"
              },
              {
                  "id": "tt14592948",
                  "rank": "49",
                  "rankUpDown": "-22",
                  "title": "Loving Adults",
                  "fullTitle": "Loving Adults (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BOWQ1ODQ0ZTQtOGJjYi00ODZmLWFkOTAtOWMzN2E4YzE0YmVjXkEyXkFqcGdeQXVyMjAwNzczNTU@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Barbara Topsøe-Rothenborg (dir.), Dar Salim, Sonja Richter",
                  "imDbRating": "6.5",
                  "imDbRatingCount": "5298"
              },
              {
                  "id": "tt1160419",
                  "rank": "50",
                  "rankUpDown": "+7",
                  "title": "Dune",
                  "fullTitle": "Dune (2021)",
                  "year": "2021",
                  "image": "https://m.media-amazon.com/images/M/MV5BN2FjNmEyNWMtYzM0ZS00NjIyLTg5YzYtYThlMGVjNzE1OGViXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Denis Villeneuve (dir.), Timothée Chalamet, Rebecca Ferguson",
                  "imDbRating": "8.0",
                  "imDbRatingCount": "610381"
              },
              {
                  "id": "tt10343028",
                  "rank": "51",
                  "rankUpDown": "1,680",
                  "title": "Armageddon Time",
                  "fullTitle": "Armageddon Time (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BZWY4Y2EzMmUtYjAyYy00NmNiLTg4Y2QtOGIzYzNkMTk1MTA5XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "James Gray (dir.), Anne Hathaway, Jeremy Strong",
                  "imDbRating": "6.6",
                  "imDbRatingCount": "282"
              },
              {
                  "id": "tt11138512",
                  "rank": "52",
                  "rankUpDown": "-9",
                  "title": "The Northman",
                  "fullTitle": "The Northman (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BMzVlMmY2NTctODgwOC00NDMzLWEzMWYtM2RiYmIyNTNhMTI0XkEyXkFqcGdeQXVyNTAzNzgwNTg@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Robert Eggers (dir.), Alexander Skarsgård, Nicole Kidman",
                  "imDbRating": "7.1",
                  "imDbRatingCount": "171449"
              },
              {
                  "id": "tt0167260",
                  "rank": "53",
                  "rankUpDown": "+10",
                  "title": "The Lord of the Rings: The Return of the King",
                  "fullTitle": "The Lord of the Rings: The Return of the King (2003)",
                  "year": "2003",
                  "image": "https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Peter Jackson (dir.), Elijah Wood, Viggo Mortensen",
                  "imDbRating": "9.0",
                  "imDbRatingCount": "1816719"
              },
              {
                  "id": "tt0068646",
                  "rank": "54",
                  "rankUpDown": "-1",
                  "title": "The Godfather",
                  "fullTitle": "The Godfather (1972)",
                  "year": "1972",
                  "image": "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Francis Ford Coppola (dir.), Marlon Brando, Al Pacino",
                  "imDbRating": "9.2",
                  "imDbRatingCount": "1830535"
              },
              {
                  "id": "tt5537002",
                  "rank": "55",
                  "rankUpDown": "+60",
                  "title": "Killers of the Flower Moon",
                  "fullTitle": "Killers of the Flower Moon (2023)",
                  "year": "2023",
                  "image": "https://m.media-amazon.com/images/M/MV5BZmMyMDc4NWMtZmUzNC00ZjczLWE1ZmYtYWQ3ZTk4ODBmYzE2XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Martin Scorsese (dir.), Leonardo DiCaprio, Robert De Niro",
                  "imDbRating": "",
                  "imDbRatingCount": "0"
              },
              {
                  "id": "tt5108870",
                  "rank": "56",
                  "rankUpDown": "+91",
                  "title": "Morbius",
                  "fullTitle": "Morbius (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BNTA3N2Q0ZTAtODJjNy00MmQzLWJlMmItOGFmNDI0ODgxN2QwXkEyXkFqcGdeQXVyMTM0NTUzNDIy._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Daniel Espinosa (dir.), Jared Leto, Matt Smith",
                  "imDbRating": "5.2",
                  "imDbRatingCount": "106969"
              },
              {
                  "id": "tt8110652",
                  "rank": "57",
                  "rankUpDown": "-9",
                  "title": "Bodies Bodies Bodies",
                  "fullTitle": "Bodies Bodies Bodies (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BYTA2ODg5ZjgtOTU2My00MzFkLWI0NzMtZmQ5MmRhMWU1NzhlXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Halina Reijn (dir.), Amandla Stenberg, Maria Bakalova",
                  "imDbRating": "6.8",
                  "imDbRatingCount": "8474"
              },
              {
                  "id": "tt1016150",
                  "rank": "58",
                  "rankUpDown": "2,470",
                  "title": "All Quiet on the Western Front",
                  "fullTitle": "All Quiet on the Western Front (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BYTE1MmZiMWYtYTFmZi00YjA3LWI2ODgtMWFlNWYxZjdmNGE3XkEyXkFqcGdeQXVyNjk1Njg5NTA@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Edward Berger (dir.), Daniel Brühl, Albrecht Schuch",
                  "imDbRating": "8.1",
                  "imDbRatingCount": "117"
              },
              {
                  "id": "tt1596342",
                  "rank": "59",
                  "rankUpDown": "+248",
                  "title": "Disenchanted",
                  "fullTitle": "Disenchanted (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BNDVhYjU1ZjUtNzI3Ni00Mzg5LWJhNGYtMjE3Y2FlZWY2Y2Y2XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Adam Shankman (dir.), Amy Adams, James Marsden",
                  "imDbRating": "",
                  "imDbRatingCount": "0"
              },
              {
                  "id": "tt8772262",
                  "rank": "60",
                  "rankUpDown": "+11",
                  "title": "Midsommar",
                  "fullTitle": "Midsommar (2019)",
                  "year": "2019",
                  "image": "https://m.media-amazon.com/images/M/MV5BMzQxNzQzOTQwM15BMl5BanBnXkFtZTgwMDQ2NTcwODM@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Ari Aster (dir.), Florence Pugh, Jack Reynor",
                  "imDbRating": "7.1",
                  "imDbRatingCount": "307472"
              },
              {
                  "id": "tt10640346",
                  "rank": "61",
                  "rankUpDown": "+455",
                  "title": "Babylon",
                  "fullTitle": "Babylon (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BZmM4MWIwMGItYzA3ZC00MDY4LTlhNWQtY2MwOTViODk1M2U1XkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Damien Chazelle (dir.), Brad Pitt, Margot Robbie",
                  "imDbRating": "",
                  "imDbRatingCount": "0"
              },
              {
                  "id": "tt8883486",
                  "rank": "62",
                  "rankUpDown": "+217",
                  "title": "Medieval",
                  "fullTitle": "Medieval (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BOTc0NTdjMTUtZGUxOC00MTkyLWFhOWUtYzc5OThiOGUwNDI4XkEyXkFqcGdeQXVyMzQwMTY2Nzk@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Petr Jákl (dir.), Ben Foster, Sophie Lowe",
                  "imDbRating": "6.4",
                  "imDbRatingCount": "721"
              },
              {
                  "id": "tt13320622",
                  "rank": "63",
                  "rankUpDown": "-19",
                  "title": "The Lost City",
                  "fullTitle": "The Lost City (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BMmIwYzFhODAtY2I1YS00ZDdmLTkyYWQtZjI5NDIwMDc2MjEyXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Aaron Nee (dir.), Sandra Bullock, Channing Tatum",
                  "imDbRating": "6.1",
                  "imDbRatingCount": "102563"
              },
              {
                  "id": "tt14298328",
                  "rank": "64",
                  "rankUpDown": "-45",
                  "title": "Look Both Ways",
                  "fullTitle": "Look Both Ways (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BYmU5ZTU3MWUtMmExZi00YjIxLWIyOWUtZTliNjFjMTEzNDEzXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Wanuri Kahiu (dir.), Lili Reinhart, Danny Ramirez",
                  "imDbRating": "6.3",
                  "imDbRatingCount": "13570"
              },
              {
                  "id": "tt7131622",
                  "rank": "65",
                  "rankUpDown": "+16",
                  "title": "Once Upon a Time in Hollywood",
                  "fullTitle": "Once Upon a Time in Hollywood (2019)",
                  "year": "2019",
                  "image": "https://m.media-amazon.com/images/M/MV5BOTg4ZTNkZmUtMzNlZi00YmFjLTk1MmUtNWQwNTM0YjcyNTNkXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Quentin Tarantino (dir.), Leonardo DiCaprio, Brad Pitt",
                  "imDbRating": "7.6",
                  "imDbRatingCount": "718348"
              },
              {
                  "id": "tt0073195",
                  "rank": "66",
                  "rankUpDown": "+37",
                  "title": "Jaws",
                  "fullTitle": "Jaws (1975)",
                  "year": "1975",
                  "image": "https://m.media-amazon.com/images/M/MV5BMmVmODY1MzEtYTMwZC00MzNhLWFkNDMtZjAwM2EwODUxZTA5XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Steven Spielberg (dir.), Roy Scheider, Robert Shaw",
                  "imDbRating": "8.1",
                  "imDbRatingCount": "599660"
              },
              {
                  "id": "tt6467266",
                  "rank": "67",
                  "rankUpDown": "-30",
                  "title": "Sing 2",
                  "fullTitle": "Sing 2 (2021)",
                  "year": "2021",
                  "image": "https://m.media-amazon.com/images/M/MV5BMWRiZGQ1NDMtODQ2OS00MDlhLWJkZGYtM2ZmNjlhZThjOWRmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Garth Jennings (dir.), Matthew McConaughey, Reese Witherspoon",
                  "imDbRating": "7.4",
                  "imDbRatingCount": "65037"
              },
              {
                  "id": "tt5862166",
                  "rank": "68",
                  "rankUpDown": "1,093",
                  "title": "The Poison Rose",
                  "fullTitle": "The Poison Rose (2019)",
                  "year": "2019",
                  "image": "https://m.media-amazon.com/images/M/MV5BMTU2NDkwNDQ5N15BMl5BanBnXkFtZTgwOTM2NTcwODM@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Francesco Cinquemani (dir.), John Travolta, Morgan Freeman",
                  "imDbRating": "4.7",
                  "imDbRatingCount": "9403"
              },
              {
                  "id": "tt11271038",
                  "rank": "69",
                  "rankUpDown": "-23",
                  "title": "Licorice Pizza",
                  "fullTitle": "Licorice Pizza (2021)",
                  "year": "2021",
                  "image": "https://m.media-amazon.com/images/M/MV5BYjkwMzIxYzMtOTVkMS00NDQxLThkMjItNzgxN2RiNjdlNTliXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Paul Thomas Anderson (dir.), Alana Haim, Cooper Hoffman",
                  "imDbRating": "7.2",
                  "imDbRatingCount": "102405"
              },
              {
                  "id": "tt0369339",
                  "rank": "70",
                  "rankUpDown": "+95",
                  "title": "Collateral",
                  "fullTitle": "Collateral (2004)",
                  "year": "2004",
                  "image": "https://m.media-amazon.com/images/M/MV5BMjE3NjM5OTMxMV5BMl5BanBnXkFtZTcwOTIzMTQyMw@@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Michael Mann (dir.), Tom Cruise, Jamie Foxx",
                  "imDbRating": "7.5",
                  "imDbRatingCount": "400773"
              },
              {
                  "id": "tt13655328",
                  "rank": "71",
                  "rankUpDown": "2,694",
                  "title": "End of the Road",
                  "fullTitle": "End of the Road (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BODE5YTA2YzMtNTY5MC00NmM4LTk5ZGYtZWE0N2ViNWJiZDMzXkEyXkFqcGdeQXVyMTAxNDE3MTE5._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Millicent Shelton (dir.), Queen Latifah, Ludacris",
                  "imDbRating": "4.7",
                  "imDbRatingCount": "4063"
              },
              {
                  "id": "tt1148204",
                  "rank": "72",
                  "rankUpDown": "-33",
                  "title": "Orphan",
                  "fullTitle": "Orphan (2009)",
                  "year": "2009",
                  "image": "https://m.media-amazon.com/images/M/MV5BMTBjMjY0ODEtZGVkMy00MjUyLTlkMjAtNDBmNzVjOTk0NzQyXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Jaume Collet-Serra (dir.), Vera Farmiga, Peter Sarsgaard",
                  "imDbRating": "7.0",
                  "imDbRatingCount": "226390"
              },
              {
                  "id": "tt0167261",
                  "rank": "73",
                  "rankUpDown": "+10",
                  "title": "The Lord of the Rings: The Two Towers",
                  "fullTitle": "The Lord of the Rings: The Two Towers (2002)",
                  "year": "2002",
                  "image": "https://m.media-amazon.com/images/M/MV5BZGMxZTdjZmYtMmE2Ni00ZTdkLWI5NTgtNjlmMjBiNzU2MmI5XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Peter Jackson (dir.), Elijah Wood, Ian McKellen",
                  "imDbRating": "8.8",
                  "imDbRatingCount": "1640504"
              },
              {
                  "id": "tt9419884",
                  "rank": "74",
                  "rankUpDown": "-20",
                  "title": "Doctor Strange in the Multiverse of Madness",
                  "fullTitle": "Doctor Strange in the Multiverse of Madness (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BNWM0ZGJlMzMtZmYwMi00NzI3LTgzMzMtNjMzNjliNDRmZmFlXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Sam Raimi (dir.), Benedict Cumberbatch, Elizabeth Olsen",
                  "imDbRating": "7.0",
                  "imDbRatingCount": "379402"
              },
              {
                  "id": "tt0111161",
                  "rank": "75",
                  "rankUpDown": "-16",
                  "title": "The Shawshank Redemption",
                  "fullTitle": "The Shawshank Redemption (1994)",
                  "year": "1994",
                  "image": "https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Frank Darabont (dir.), Tim Robbins, Morgan Freeman",
                  "imDbRating": "9.3",
                  "imDbRatingCount": "2640785"
              },
              {
                  "id": "tt1464335",
                  "rank": "76",
                  "rankUpDown": "-40",
                  "title": "Uncharted",
                  "fullTitle": "Uncharted (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BMWEwNjhkYzYtNjgzYy00YTY2LThjYWYtYzViMGJkZTI4Y2MyXkEyXkFqcGdeQXVyNTM0OTY1OQ@@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Ruben Fleischer (dir.), Tom Holland, Mark Wahlberg",
                  "imDbRating": "6.3",
                  "imDbRatingCount": "183263"
              },
              {
                  "id": "tt11813216",
                  "rank": "77",
                  "rankUpDown": "+865",
                  "title": "The Banshees of Inisherin",
                  "fullTitle": "The Banshees of Inisherin (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BM2NlZDI0ZDktNTg5OS00ZjQ1LWI4MDEtN2I0MDE5NWRiNzA4XkEyXkFqcGdeQXVyMTY5Nzc4MDY@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Martin McDonagh (dir.), Colin Farrell, Brendan Gleeson",
                  "imDbRating": "8.1",
                  "imDbRatingCount": "298"
              },
              {
                  "id": "tt15315164",
                  "rank": "78",
                  "rankUpDown": "+8",
                  "title": "Cuttputli",
                  "fullTitle": "Cuttputli (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BYzZmYjBiMzQtYWQwMC00ZWJiLWEzZDItNGJlODRlODRkZWNmXkEyXkFqcGdeQXVyOTI3MzI4MzA@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Ranjit Tewari (dir.), Akshay Kumar, Rakul Preet Singh",
                  "imDbRating": "5.9",
                  "imDbRatingCount": "16879"
              },
              {
                  "id": "tt14614892",
                  "rank": "79",
                  "rankUpDown": "-46",
                  "title": "Dragon Ball Super: Super Hero",
                  "fullTitle": "Dragon Ball Super: Super Hero (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BZmFjNzkwOGYtMzBlYS00NmI4LWIwOTAtMDhhMjY4ZDkwNzI0XkEyXkFqcGdeQXVyODUyNjMyOTE@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Tetsuro Kodama (dir.), Masako Nozawa, Toshio Furukawa",
                  "imDbRating": "7.2",
                  "imDbRatingCount": "7273"
              },
              {
                  "id": "tt0903624",
                  "rank": "80",
                  "rankUpDown": "+8",
                  "title": "The Hobbit: An Unexpected Journey",
                  "fullTitle": "The Hobbit: An Unexpected Journey (2012)",
                  "year": "2012",
                  "image": "https://m.media-amazon.com/images/M/MV5BMTcwNTE4MTUxMl5BMl5BanBnXkFtZTcwMDIyODM4OA@@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Peter Jackson (dir.), Martin Freeman, Ian McKellen",
                  "imDbRating": "7.8",
                  "imDbRatingCount": "818614"
              },
              {
                  "id": "tt10304142",
                  "rank": "81",
                  "rankUpDown": "+123",
                  "title": "Amsterdam",
                  "fullTitle": "Amsterdam (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BYjkwODBlMjMtNDgxZS00ODQyLTk1NDMtNThkMDRjNGFlMDMyXkEyXkFqcGdeQXVyOTk2Mzg0MzE@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "David O. Russell (dir.), Christian Bale, Margot Robbie",
                  "imDbRating": "",
                  "imDbRatingCount": "0"
              },
              {
                  "id": "tt15558152",
                  "rank": "82",
                  "rankUpDown": "+745",
                  "title": "The Visitor",
                  "fullTitle": "The Visitor (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BNjFhMzM4MWUtNDY4YS00NTY2LWIwMTUtYzBmMzMzYzEwZDVlXkEyXkFqcGdeQXVyMjY5ODI4NDk@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Justin P. Lange (dir.), Jessica McNamee, Finn Jones",
                  "imDbRating": "",
                  "imDbRatingCount": "0"
              },
              {
                  "id": "tt5834426",
                  "rank": "83",
                  "rankUpDown": "+44",
                  "title": "Moonfall",
                  "fullTitle": "Moonfall (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BZjk0OWZiN2ItNmQ2YS00NTJmLTg0MjItNzM4NzBkMWM1ZTRlXkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Roland Emmerich (dir.), Halle Berry, Patrick Wilson",
                  "imDbRating": "5.1",
                  "imDbRatingCount": "68491"
              },
              {
                  "id": "tt1630029",
                  "rank": "84",
                  "rankUpDown": "-34",
                  "title": "Avatar: The Way of Water",
                  "fullTitle": "Avatar: The Way of Water (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BMWFmYmRiYzMtMTQ4YS00NjA5LTliYTgtMmM3OTc4OGY3MTFkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "James Cameron (dir.), Michelle Yeoh, Zoe Saldana",
                  "imDbRating": "",
                  "imDbRatingCount": "0"
              },
              {
                  "id": "tt18925334",
                  "rank": "85",
                  "rankUpDown": "+184",
                  "title": "Pearl",
                  "fullTitle": "Pearl (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BZTFkNmE5MjUtZDE1Yi00ZmQyLTk2YWUtN2EwODA1ZmNlOTA5XkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Ti West (dir.), David Corenswet, Mia Goth",
                  "imDbRating": "7.5",
                  "imDbRatingCount": "1326"
              },
              {
                  "id": "tt0107120",
                  "rank": "86",
                  "rankUpDown": "+18",
                  "title": "Hocus Pocus",
                  "fullTitle": "Hocus Pocus (1993)",
                  "year": "1993",
                  "image": "https://m.media-amazon.com/images/M/MV5BMWUxNWI0YTYtY2RiZS00ZjNmLTg4ZGUtNDI0Mzk4NmQ5NWE5XkEyXkFqcGdeQXVyNjk1Njg5NTA@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Kenny Ortega (dir.), Bette Midler, Sarah Jessica Parker",
                  "imDbRating": "6.9",
                  "imDbRatingCount": "123970"
              },
              {
                  "id": "tt13139228",
                  "rank": "87",
                  "rankUpDown": "+706",
                  "title": "My Policeman",
                  "fullTitle": "My Policeman (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BNzgxYjMxY2MtZDMzNS00MDVkLWI5MmUtMmY0MTNmY2MzZTAzXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Michael Grandage (dir.), Harry Styles, Emma Corrin",
                  "imDbRating": "7.1",
                  "imDbRatingCount": "132"
              },
              {
                  "id": "tt5113044",
                  "rank": "88",
                  "rankUpDown": "-20",
                  "title": "Minions: The Rise of Gru",
                  "fullTitle": "Minions: The Rise of Gru (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BZDQyODUwM2MtNzA0YS00ZjdmLTgzMjItZWRjN2YyYWE5ZTNjXkEyXkFqcGdeQXVyMTI2MzY1MjM1._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Kyle Balda (dir.), Steve Carell, Pierre Coffin",
                  "imDbRating": "6.6",
                  "imDbRatingCount": "52701"
              },
              {
                  "id": "tt8946378",
                  "rank": "89",
                  "rankUpDown": "+57",
                  "title": "Knives Out",
                  "fullTitle": "Knives Out (2019)",
                  "year": "2019",
                  "image": "https://m.media-amazon.com/images/M/MV5BMGUwZjliMTAtNzAxZi00MWNiLWE2NzgtZGUxMGQxZjhhNDRiXkEyXkFqcGdeQXVyNjU1NzU3MzE@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Rian Johnson (dir.), Daniel Craig, Chris Evans",
                  "imDbRating": "7.9",
                  "imDbRatingCount": "610160"
              },
              {
                  "id": "tt0499549",
                  "rank": "90",
                  "rankUpDown": "+43",
                  "title": "Avatar",
                  "fullTitle": "Avatar (2009)",
                  "year": "2009",
                  "image": "https://m.media-amazon.com/images/M/MV5BNjA3NGExZDktNDlhZC00NjYyLTgwNmUtZWUzMDYwMTZjZWUyXkEyXkFqcGdeQXVyMTU1MDM3NDk0._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "James Cameron (dir.), Sam Worthington, Zoe Saldana",
                  "imDbRating": "7.8",
                  "imDbRatingCount": "1221707"
              },
              {
                  "id": "tt10298810",
                  "rank": "91",
                  "rankUpDown": "-36",
                  "title": "Lightyear",
                  "fullTitle": "Lightyear (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BYTg2Zjk0ZTctM2ZmMi00MDRmLWJjOGYtNWM0YjBmZTBjMjRkXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Angus MacLane (dir.), Chris Evans, Keke Palmer",
                  "imDbRating": "5.9",
                  "imDbRatingCount": "92405"
              },
              {
                  "id": "tt9731598",
                  "rank": "92",
                  "rankUpDown": "+13",
                  "title": "Bros",
                  "fullTitle": "Bros (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BNDA5OTdjMTMtZTQ4Zi00ODUwLWI1YjMtY2EwNGZhY2MwNjBlXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Nicholas Stoller (dir.), Luke Macfarlane, Billy Eichner",
                  "imDbRating": "5.7",
                  "imDbRatingCount": "404"
              },
              {
                  "id": "tt7657566",
                  "rank": "93",
                  "rankUpDown": "-33",
                  "title": "Death on the Nile",
                  "fullTitle": "Death on the Nile (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BNjI4ZTQ1OTYtNTI0Yi00M2EyLThiNjMtMzk1MmZlOWMyMDQwXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Kenneth Branagh (dir.), Tom Bateman, Annette Bening",
                  "imDbRating": "6.3",
                  "imDbRatingCount": "138366"
              },
              {
                  "id": "tt0241527",
                  "rank": "94",
                  "rankUpDown": "-17",
                  "title": "Harry Potter and the Sorcerer's Stone",
                  "fullTitle": "Harry Potter and the Sorcerer's Stone (2001)",
                  "year": "2001",
                  "image": "https://m.media-amazon.com/images/M/MV5BMzkyZGFlOWQtZjFlMi00N2YwLWE2OWQtYTgxY2NkNmM1NjMwXkEyXkFqcGdeQXVyNjY1NTM1MzA@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Chris Columbus (dir.), Daniel Radcliffe, Rupert Grint",
                  "imDbRating": "7.6",
                  "imDbRatingCount": "767113"
              },
              {
                  "id": "tt1488589",
                  "rank": "95",
                  "rankUpDown": "+178",
                  "title": "Guillermo del Toro's Pinocchio",
                  "fullTitle": "Guillermo del Toro's Pinocchio (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BZGYyOTg1NzMtZDc1ZS00MTQ2LTk4MGMtOThjNjY1MGJkODIxXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Guillermo del Toro (dir.), Gregory Mann, Ewan McGregor",
                  "imDbRating": "",
                  "imDbRatingCount": "0"
              },
              {
                  "id": "tt4614584",
                  "rank": "96",
                  "rankUpDown": "-47",
                  "title": "Purple Hearts",
                  "fullTitle": "Purple Hearts (2022)",
                  "year": "2022",
                  "image": "https://m.media-amazon.com/images/M/MV5BNzI4ZTAwNzEtNTk5YS00ZWJmLWI1ODMtOTU4MTM5MzQ4OWM0XkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Elizabeth Allen Rosenbaum (dir.), Sofia Carson, Nicholas Galitzine",
                  "imDbRating": "6.7",
                  "imDbRatingCount": "32072"
              },
              {
                  "id": "tt5052448",
                  "rank": "97",
                  "rankUpDown": "-39",
                  "title": "Get Out",
                  "fullTitle": "Get Out (2017)",
                  "year": "2017",
                  "image": "https://m.media-amazon.com/images/M/MV5BMjUxMDQwNjcyNl5BMl5BanBnXkFtZTgwNzcwMzc0MTI@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Jordan Peele (dir.), Daniel Kaluuya, Allison Williams",
                  "imDbRating": "7.7",
                  "imDbRatingCount": "592556"
              },
              {
                  "id": "tt12789558",
                  "rank": "98",
                  "rankUpDown": "-3",
                  "title": "Belfast",
                  "fullTitle": "Belfast (2021)",
                  "year": "2021",
                  "image": "https://m.media-amazon.com/images/M/MV5BODMwYTYyY2ItOWQ5Yi00OTI1LTllYTQtYTdlNWM4YzJhYTM0XkEyXkFqcGdeQXVyMTA2MDU0NjM5._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Kenneth Branagh (dir.), Jude Hill, Lewis McAskie",
                  "imDbRating": "7.3",
                  "imDbRatingCount": "69075"
              },
              {
                  "id": "tt8550054",
                  "rank": "99",
                  "rankUpDown": "+91",
                  "title": "Pleasure",
                  "fullTitle": "Pleasure (2021)",
                  "year": "2021",
                  "image": "https://m.media-amazon.com/images/M/MV5BNmU3ZTJjMTEtYzc2Ny00YjVhLTkyYmQtZTFhYWY0N2MxMzkxXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Ninja Thyberg (dir.), Sofia Kappel, Zelda Morrison",
                  "imDbRating": "6.3",
                  "imDbRatingCount": "14674"
              },
              {
                  "id": "tt0816692",
                  "rank": "100",
                  "rankUpDown": "-15",
                  "title": "Interstellar",
                  "fullTitle": "Interstellar (2014)",
                  "year": "2014",
                  "image": "https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX128_CR0,12,128,176_AL_.jpg",
                  "crew": "Christopher Nolan (dir.), Matthew McConaughey, Anne Hathaway",
                  "imDbRating": "8.6",
                  "imDbRatingCount": "1783797"
              }
          ],
          "errorMessage": ""
        }
      })
  },[]);
  console.log(data);
  return (
    <div className="App bg-[#10141f] h-full text-white">
        <Header />
        <div className="w-full h-60 md:h-80 bg-gradient-to-br from-cyan-400 to-violet-700"></div>
        <div className="w-full h-60 md:h-80 bg-gradient-to-tr from-cyan-400 to-violet-700"></div>
        {data.items&&<Section {...data} />}
    </div>
  );
}

export default App;
